apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-deploy-2401034-v2
  namespace: student-2401034
  labels:
    app: loan-app-2401034-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-app-2401034-v2
  template:
    metadata:
      labels:
        app: loan-app-2401034-v2
    spec:
      containers:
        - name: loan-container
          image: nexus.imcc.com:8083/docker-hosted/loan-app-2401034-v2:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
