# --------------------------------
# Deployment (no PVC needed)
# --------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-app-deployment
  namespace: "2401034"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-app
  template:
    metadata:
      labels:
        app: loan-app
    spec:
      imagePullSecrets:
        - name: nexus-secret

      containers:
        - name: loan-app
          image: 127.0.0.1:30085/2401034-project/loan-app-2401034-v2:latest
          ports:
            - containerPort: 8000

          env:
            - name: DEBUG
              value: "0"

          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30


---
# --------------------------------
# Service (NodePort + Ingress Compatible)
# --------------------------------
apiVersion: v1
kind: Service
metadata:
  name: loan-app-service
  namespace: "2401034"
spec:
  selector:
    app: loan-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30244


---
# --------------------------------
# Ingress (Domain Routing)
# --------------------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loan-app-ingress
  namespace: "2401034"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: loan.imcc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loan-app-service
                port:
                  number: 80
