apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-app-deployment
  labels:
    app: loan-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-app
  template:
    metadata:
      labels:
        app: loan-app
    spec:
      containers:
        - name: loan-app
          image: loan-app:latest   # change to your Nexus image later
          ports:
            - containerPort: 8000
