apiVersion: v1
kind: Service
metadata:
  name: loan-app-service
  namespace: "2401034"
spec:
  selector:
    app: loan-app      # MUST match deployment label
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30244
   # REQUIRED (teacher testing value)
